version: '3.1'

services:
  express:
    image: htmx-test/express
    ports: 
      - "3000:3000"
  mongo:
    image: mongo
    restart: always
    volumes: 
      - "/tmp/htmx-test:/data/db"
    ports:
      - "27017:27017"
